-- Run once in Supabase SQL Editor.
-- Adds manager-only product data and allows the app to read/write customer activity.

alter table public.products add column if not exists supplier text;
alter table public.products add column if not exists stock integer not null default 0;
alter table public.products add column if not exists out_of_stock boolean not null default false;
alter table public.products add column if not exists colors jsonb not null default '["قياسي"]'::jsonb;

create table if not exists public.product_reviews (
	id bigint generated by default as identity primary key,
	product_name text not null,
	reviewer_name text not null default 'زبون زائر',
	phone text,
	rating numeric not null default 5,
	comment text not null,
	created_at timestamptz not null default now()
);

alter table public.product_reviews add column if not exists phone text;

create table if not exists public.store_messages (
	id bigint generated by default as identity primary key,
	customer_phone text not null,
	customer_contact text,
	sender_role text not null,
	sender_name text not null,
	message text not null,
	created_at timestamptz not null default now()
);

alter table public.store_messages add column if not exists customer_contact text;
alter table public.store_messages alter column customer_phone drop not null;
update public.store_messages
set customer_contact = customer_phone
where customer_contact is null;

alter table public.orders enable row level security;
alter table public.product_reviews enable row level security;
alter table public.store_messages enable row level security;

drop policy if exists "Anyone can read store messages" on public.store_messages;
create policy "Anyone can read store messages"
on public.store_messages for select to anon, authenticated using (true);

drop policy if exists "Anyone can create store messages" on public.store_messages;
create policy "Anyone can create store messages"
on public.store_messages for insert to anon, authenticated with check (true);

 drop policy if exists "Anyone can create orders" on public.orders;
create policy "Anyone can create orders"
on public.orders for insert to anon, authenticated with check (true);

 drop policy if exists "Authenticated admins can read orders" on public.orders;
create policy "Authenticated admins can read orders"
on public.orders for select to authenticated using (true);

 drop policy if exists "Authenticated admins can update orders" on public.orders;
create policy "Authenticated admins can update orders"
on public.orders for update to authenticated using (true) with check (true);

 drop policy if exists "Authenticated admins can delete orders" on public.orders;
create policy "Authenticated admins can delete orders"
on public.orders for delete to authenticated using (true);

 drop policy if exists "Anyone can read product reviews" on public.product_reviews;
create policy "Anyone can read product reviews"
on public.product_reviews for select to anon, authenticated using (true);

 drop policy if exists "Anyone can create product reviews" on public.product_reviews;
create policy "Anyone can create product reviews"
on public.product_reviews for insert to anon, authenticated with check (true);

 drop policy if exists "Authenticated admins can delete product reviews" on public.product_reviews;
create policy "Authenticated admins can delete product reviews"
on public.product_reviews for delete to authenticated using (true);
